name: Markdown Lint and Spell Check

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - '**/*.md'
  push:
    branches: [ main, master ]
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
      
    - name: Install cspell
      run: npm install -g cspell
      
    - name: Run markdownlint
      run: markdownlint "**/*.md" --ignore node_modules
      
    - name: Run spell check
      run: cspell "**/*.md" --config .cspell.json
      
    - name: Check for broken links
      run: |
        npm install -g markdown-link-check
        find . -name "*.md" -not -path "./node_modules/*" -exec markdown-link-check {} \;
